# Generated by Django 3.0.5 on 2020-07-27 02:07

from django.db import migrations, models
import django.utils.timezone
import django_mysql.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTr',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('volume', models.IntegerField()),
                ('scope', models.CharField(max_length=128)),
                ('year', models.DateField()),
                ('questions', django_mysql.models.ListCharField(models.CharField(max_length=128), max_length=128, size=None)),
                ('answers', django_mysql.models.ListCharField(models.CharField(max_length=128), max_length=128, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTr',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('exam_class', models.CharField(max_length=128)),
                ('year', models.DateField()),
                ('select1', models.CharField(max_length=128)),
                ('select2', models.CharField(max_length=128)),
                ('select3', models.CharField(max_length=128)),
                ('select4', models.CharField(max_length=128)),
                ('select5', models.CharField(max_length=128)),
                ('select6', models.CharField(max_length=128)),
                ('select7', models.CharField(max_length=128)),
                ('select8', models.CharField(max_length=128)),
                ('select9', models.CharField(max_length=128)),
                ('select10', models.CharField(max_length=128)),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
