# Generated by Django 3.0.5 on 2020-07-28 18:21

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtr',
            name='answers',
            field=django_mysql.models.ListCharField(models.CharField(max_length=128, null=True), max_length=128, size=None),
        ),
        migrations.AlterField(
            model_name='examtr',
            name='questions',
            field=django_mysql.models.ListCharField(models.CharField(max_length=128, null=True), max_length=128, size=None),
        ),
        migrations.AlterField(
            model_name='questiontr',
            name='select10',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='questiontr',
            name='select5',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='questiontr',
            name='select6',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='questiontr',
            name='select7',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='questiontr',
            name='select8',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='questiontr',
            name='select9',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
