# Generated by Django 3.0.5 on 2020-08-05 05:13

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20200728_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtr',
            name='questions',
            field=django_mysql.models.ListCharField(models.CharField(max_length=512, null=True), max_length=128, size=None),
        ),
    ]
