# Generated by Django 3.0.5 on 2020-08-05 05:23

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20200805_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtr',
            name='questions',
            field=django_mysql.models.ListCharField(models.CharField(max_length=128, null=True), max_length=512, size=None),
        ),
    ]
