# Generated by Django 3.0.5 on 2020-08-05 09:01

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20200805_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtr',
            name='questions',
            field=django_mysql.models.ListCharField(models.CharField(max_length=128, null=True), max_length=10240, size=None),
        ),
    ]
