# Generated by Django 3.0.5 on 2020-08-05 15:35

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20200805_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtr',
            name='answers',
            field=django_mysql.models.ListCharField(models.CharField(max_length=4, null=True), max_length=512, size=None),
        ),
        migrations.AlterField(
            model_name='examtr',
            name='questions',
            field=django_mysql.models.ListCharField(models.CharField(max_length=32, null=True), max_length=5120, size=None),
        ),
    ]
